// Customer sees a separate delivery fee at checkout; product prices include the remaining courier cost.
const PRODUCTS = [
  { id:'mango-1kg', name:'Mango Pulp Drink Premix 1kg', description:'Refreshing mango drink premix for easy homemade mango juice — makes approximately 9.8–10 liters.', price:450, oldPrice:600, weight:1, image:'assets/products/1kg-mango-pulp.webp', tag:'POPULAR', bestSellerRank:2, newProductRank:1 },
  { id:'mango-2kg', name:'Mango Pulp Drink Premix 2kg', description:'Refreshing mango drink premix for easy homemade mango juice — makes approximately 19.6–20 liters.', price:795, oldPrice:1290, weight:2, image:'assets/products/2kg-mango-pulp.jpg', tag:'DEAL', bestSellerRank:3, newProductRank:2 },
  { id:'mango-3kg', name:'Mango Pulp Drink Premix 3kg', description:'Liquid mango pulp mix for larger family use — makes approximately 29.4–30 liters.', price:1214, oldPrice:1680, weight:3, image:'assets/products/3kg-mango-pulp.webp', tag:'BEST SELLER', bestSellerRank:1, newProductRank:3 },
  { id:'mango-4kg', name:'Mango Pulp Drink Premix 4kg', description:'Family-size mango drink premix — makes approximately 39.2–40 liters.', price:1650, oldPrice:2270, weight:4, image:'assets/products/4kg-mango-pulp.webp', tag:'VALUE', bestSellerRank:5, newProductRank:4 },
  { id:'mango-5kg', name:'Mango Pulp Drink Premix 5kg', description:'1kg × 5 pack for larger gatherings — makes approximately 49–50 liters.', price:2130, oldPrice:3030, weight:5, image:'assets/products/5kg-mango-pulp.jpg', tag:'VALUE PACK', bestSellerRank:4, newProductRank:6 },
  { id:'mango-10kg', name:'Mango Pulp Drink Premix 10kg', description:'Large 10kg pack for events, families and bulk use — makes approximately 98–100 liters.', price:4130, oldPrice:5530, weight:10, image:'assets/products/10kg-mango-pulp.webp', tag:'BULK PACK', bestSellerRank:6, newProductRank:5 }
];
